# Generated by Django 5.1.2 on 2024-10-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default='2024-10-23'),
        ),
    ]
