# Generated by Django 5.1.2 on 2024-10-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_country_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
    ]
