# Generated by Django 5.1.2 on 2024-10-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_remove_country_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='country_id',
            new_name='country',
        ),
    ]
