# Generated by Django 5.1.2 on 2024-10-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_rename_country_id_state_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
    ]
